#include<stdio.h>
struct student{
    int rollNo;
    char name[50];
    float marks;
};
int main(){
    struct student s1={51,"Shraven",80.5};
    struct student s2={52,"Sriniketh",89.5};
    struct student s3={53,"Sunil",79};
    struct student s4={54,"Suvetha Bharathi",87};
    struct student s5={55,"Swathi",88};
    struct student s6={56,"Tamilselvan",77};
    struct student s7={57,"Valan Raj",89.5};
    struct student s8={58,"Vishal",60.5};
    struct student s9={59,"Yogalakshmi",83.5};
    printf("Roll Number:%d\n",s1.rollNo);
    printf("Name:%s\n",s1.name);
    printf("Marks:%f\n",s1.marks);
    printf("\n");
    printf("Roll Number:%d\n",s2.rollNo);
    printf("Name:%s\n",s2.name);
    printf("Marks:%f\n",s2.marks);
    printf("\n");
    printf("Roll Number:%d\n",s3.rollNo);
    printf("Name:%s\n",s3.name);
    printf("Marks:%f\n",s3.marks);
    printf("\n");
    printf("Roll Number:%d\n",s4.rollNo);
    printf("Name:%s\n",s4.name);
    printf("Marks:%f\n",s4.marks);
    printf("\n");
    printf("Roll Number:%d\n",s5.rollNo);
    printf("Name:%s\n",s5.name);
    printf("Marks:%f\n",s5.marks);
    printf("\n");
    printf("Roll Number:%d\n",s6.rollNo);
    printf("Name:%s\n",s6.name);
    printf("Marks:%f\n",s6.marks);
    printf("\n");
    printf("Roll Number:%d\n",s7.rollNo);
    printf("Name:%s\n",s7.name);
    printf("Marks:%f\n",s7.marks);
    printf("\n");
    printf("Roll Number:%d\n",s8.rollNo);
    printf("Name:%s\n",s8.name);
    printf("Marks:%f\n",s8.marks);
    printf("\n");
    printf("Roll Number:%d\n",s9.rollNo);
    printf("Name:%s\n",s9.name);
    printf("Marks:%f\n",s9.marks);
    return 0;
}
